// Auto-generated by AI test runner — do not edit manually.
// Spec: create-employee

import { test, expect } from '../../../src/fixtures/base.fixture';

test.describe('create-employee', () => {
  test('create-employee', async ({ page }) => {
    const timestamp = Date.now();
    const adminEmail = `e2e+${timestamp}@test.clockshark.com`;
    const empEmail = `e2e+emp+${timestamp}@test.clockshark.com`;

    // Step 1: Navigate to Login
    await page.goto('/Login');

    // Step 2: Click Sign up
    await page.getByRole('link', { name: 'Sign up' }).click();
    await expect(page).toHaveURL(/\/Signup/, { timeout: 30000 });

    // Step 3: Register with unique email
    await page.getByRole('textbox', { name: 'Work Email' }).fill(adminEmail);
    await page.getByRole('textbox', { name: 'Password' }).fill('TestPass123!');
    await page.getByRole('checkbox', { name: /I agree to the ClockShark/ }).click();
    await page.getByRole('button', { name: 'Try Free for 14 Days' }).click();

    // Wait for redirect to onboarding
    await expect(page).toHaveURL(/\/App\/Welcome/, { timeout: 30000 });

    // Step 4: Onboarding Step 1 — personal info
    await page.getByLabel('First Name').fill('Test');
    await page.getByLabel('Last Name').fill('Admin');
    await page.getByLabel('Work Phone').fill('5559876543');
    await page.locator('#step-1').getByText('Next').click();

    // Step 5: Onboarding Step 2 — company info
    // Industry <select> value is 'Construction' (displayed text is 'Construction/Trade')
    // Country <select> value is '236' (displayed text is 'United States')
    // State <select> value is '4062' (displayed text is 'California')
    await page.getByLabel('Company Name').fill('E2E Employee Test Co');
    await page.getByLabel('Industry Type').selectOption('Construction');
    await page.getByLabel('Number of Employees').selectOption('1-10');
    await page.getByLabel('Country', { exact: true }).selectOption('236');
    await page.getByLabel('State / Province').selectOption('4062');
    await page.locator('#step-2').getByText('Next').click();

    // Step 6: Onboarding Step 3 — skip mobile app download
    await page.getByText("I'll do this later").click();
    await expect(page).toHaveURL(/\/App\/TimeSheets/, { timeout: 30000 });

    // Remove Chameleon highlight overlay — it spawns repeatedly and intercepts pointer events
    await page.evaluate(() => { document.getElementById('chmln-dom')?.remove(); });

    // Step 7: Navigate to Admin > Employees
    await page.getByRole('button', { name: /Admin/ }).click();
    await page.getByRole('link', { name: 'Employees' }).click();
    await expect(page).toHaveURL(/\/App\/Employees/, { timeout: 30000 });

    // Remove Chameleon overlay again after navigation
    await page.evaluate(() => { document.getElementById('chmln-dom')?.remove(); });

    // Step 8: Click Add Employee
    await page.getByRole('link', { name: 'Add Employee' }).click();

    // Steps 9–12: Fill employee form
    await page.getByPlaceholder('First Name').fill('Jane');
    await page.getByPlaceholder('Last Name').fill('Doe');
    await page.getByLabel('Email').fill(empEmail);
    await page.getByLabel(/Temporary Password/).fill('EmployeePass123!');

    // Remove Chameleon overlay before submitting
    await page.evaluate(() => { document.getElementById('chmln-dom')?.remove(); });

    // Step 13: Create the employee
    await page.getByText('Create Employee').click();

    // Step 14: Wait for modal to close — new employee appears in the table
    await expect(page.getByRole('cell', { name: 'Jane' })).toBeVisible({ timeout: 30000 });
  });
});
