import { spawnSync } from 'node:child_process';
import { readFile } from 'node:fs/promises';
import { resolve, dirname, relative } from 'node:path';
import type { AgentResult, SpecFile } from './types.js';

/**
 * Compute the relative import path from generated test to fixture.
 */
function computeFixtureImport(generatedTestPath: string): string {
  const testDir = dirname(generatedTestPath);
  let rel = relative(testDir, 'src/fixtures/base.fixture');
  rel = rel.split('\\').join('/');
  if (!rel.startsWith('.')) rel = './' + rel;
  return rel;
}

function buildPrompt(spec: SpecFile, projectRoot: string, previousFailure?: string): string {
  const fixtureImport = computeFixtureImport(spec.frontmatter.generated_test);
  const absTestPath = resolve(projectRoot, spec.frontmatter.generated_test)
    .split('\\')
    .join('/');

  return `You are an E2E test executor. Execute the following test specification against the live web app using the Playwright browser tools, then write a deterministic Playwright test file capturing exactly what you did.

## Application Context
${spec.context || 'No additional context.'}

## Test Data
${spec.data || 'Generate unique data where needed (e.g., use timestamps for unique emails).'}

## Steps
${spec.steps}

## Assertions
${spec.assertions}

## Execution Instructions
1. Take a page snapshot first to see the current state.
2. Execute each step. Use the accessibility/aria snapshot to find the right elements.
3. Verify each assertion after the relevant step.
4. If a step fails, try alternative selectors (up to 3 attempts).

## After Successful Execution
Write a Playwright test file to: ${absTestPath}

Test file format:
\`\`\`typescript
// Auto-generated by AI test runner — do not edit manually.
// Spec: ${spec.frontmatter.id}

import { test, expect } from '${fixtureImport}';

test.describe('${spec.frontmatter.id}', () => {
  test('${spec.frontmatter.id}', async ({ page }) => {
    // ... flat Playwright calls matching exactly what you did ...
  });
});
\`\`\`

Rules for the test file:
- Use flat Playwright calls only (page.getByRole, page.locator, etc.) — no page objects
- For unique emails, use template literals with \${Date.now()} instead of hardcoded timestamps
- CRITICAL: For URL assertions, ALWAYS use the async form: \`await expect(page).toHaveURL(/pattern/)\`
  NEVER use the synchronous form: \`expect(page.url()).toContain(...)\` — it races with navigation and causes flaky tests
- For visibility assertions: \`await expect(locator).toBeVisible()\`
- For text assertions: \`await expect(locator).toContainText('...')\`
- All assertions MUST be awaited — Playwright assertions are async and auto-retry
- Do NOT include snapshot/observation calls — only actionable steps and assertions
- Add { timeout: 30000 } to any waitForURL or navigation that may take time${previousFailure ? `

## IMPORTANT: Previous Attempt Failed
A previously generated test failed during the stability gate. Here is the error output.
You MUST fix whatever caused this failure in the new test you write. Analyze the error carefully and adjust selectors, waits, or assertions accordingly.

\`\`\`
${previousFailure.slice(0, 2000)}
\`\`\`` : ''}`;
}

export interface CliAgentOptions {
  onStatus?: (message: string) => void;
  baseUrl?: string;
  /** Error output from a previous stability gate failure — helps the agent fix the test */
  previousFailure?: string;
}

/**
 * Run the AI agent via Claude Code CLI.
 * Uses the user's authenticated Claude Code session — no API key needed.
 * Claude Code uses Playwright MCP to drive the browser and writes the test file directly.
 *
 * Prerequisites:
 * - Claude Code CLI installed: npm install -g @anthropic-ai/claude-code
 * - Playwright MCP server configured in Claude Code settings
 */
export async function runAgentCli(
  spec: SpecFile,
  projectRoot: string,
  options: CliAgentOptions = {},
): Promise<AgentResult> {
  const prompt = buildPrompt(spec, projectRoot, options.previousFailure);
  const absTestPath = resolve(projectRoot, spec.frontmatter.generated_test);

  options.onStatus?.('Invoking Claude Code CLI...');

  try {
    // Use spawnSync with shell:true so Windows can resolve `claude.cmd`.
    // Prompt is piped via stdin to avoid command-line length limits.
    const proc = spawnSync('claude', [
      '-p',
      '--output-format', 'json',
      '--allowedTools', 'mcp__playwright__browser_navigate,mcp__playwright__browser_navigate_back,mcp__playwright__browser_click,mcp__playwright__browser_type,mcp__playwright__browser_fill_form,mcp__playwright__browser_hover,mcp__playwright__browser_press_key,mcp__playwright__browser_snapshot,mcp__playwright__browser_take_screenshot,mcp__playwright__browser_wait_for,mcp__playwright__browser_select_option,mcp__playwright__browser_handle_dialog,mcp__playwright__browser_evaluate,mcp__playwright__browser_tabs,mcp__playwright__browser_close,Write,Edit,Read',
    ], {
      cwd: projectRoot,
      input: prompt,
      shell: true,
      timeout: 300_000, // 5 min
      maxBuffer: 10 * 1024 * 1024,
      env: {
        ...process.env,
        CLAUDECODE: undefined,
      },
    });

    if (proc.error) {
      throw proc.error;
    }

    if (proc.stderr && proc.stderr.length > 0) {
      options.onStatus?.(`Claude stderr: ${proc.stderr.toString('utf-8').slice(0, 300)}`);
    }

    const output = proc.stdout?.toString('utf-8') ?? '';
    const stderrStr = proc.stderr?.toString('utf-8') ?? '';
    options.onStatus?.(`Claude Code response (${output.length} chars, exit=${proc.status})`);

    // Handle non-zero exit or empty output
    if (proc.status !== 0 || !output.trim()) {
      const detail = stderrStr || output || 'No output from Claude Code CLI';
      // Check for common "not found" patterns
      if (
        detail.includes('ENOENT') ||
        detail.includes('not found') ||
        detail.includes('not recognized') ||
        detail.includes("is not recognized as")
      ) {
        return {
          success: false,
          actionLog: [],
          error: 'Claude Code CLI (claude) not found. Install: npm install -g @anthropic-ai/claude-code',
          tokenUsage: { inputTokens: 0, outputTokens: 0 },
        };
      }
      return {
        success: false,
        actionLog: [],
        error: `Claude Code CLI exited with code ${proc.status}: ${detail.slice(0, 500)}`,
        tokenUsage: { inputTokens: 0, outputTokens: 0 },
      };
    }

    let parsed: { result?: string; is_error?: boolean } | null = null;

    try {
      parsed = JSON.parse(output);
    } catch {
      parsed = { result: output };
    }

    // Log what Claude returned for debugging
    const responsePreview = parsed?.result
      ? parsed.result.slice(0, 500)
      : output.slice(0, 500);
    options.onStatus?.(`Response preview: ${responsePreview}`);

    if (parsed?.is_error) {
      return {
        success: false,
        actionLog: [],
        error: parsed.result ?? 'Claude Code CLI returned an error',
        tokenUsage: { inputTokens: 0, outputTokens: 0 },
      };
    }

    // Verify the test file was written
    try {
      await readFile(absTestPath, 'utf-8');
      options.onStatus?.('Test file written by Claude Code');
      return {
        success: true,
        actionLog: [],
        tokenUsage: { inputTokens: 0, outputTokens: 0 },
      };
    } catch {
      return {
        success: false,
        actionLog: [],
        error:
          `Claude Code completed but test file was not written to ${absTestPath}. ` +
          `Response: ${responsePreview}`,
        tokenUsage: { inputTokens: 0, outputTokens: 0 },
      };
    }
  } catch (error) {
    const message = error instanceof Error ? error.message : String(error);
    return {
      success: false,
      actionLog: [],
      error: `Claude Code CLI failed: ${message}`,
      tokenUsage: { inputTokens: 0, outputTokens: 0 },
    };
  }
}
