// Auto-generated by AI test runner — do not edit manually.
// Spec: signup-flow

import { test, expect } from '../../../src/fixtures/base.fixture';

test.describe('signup-flow', () => {
  test('signup-flow', async ({ page }) => {
    const email = `e2e+${Date.now()}@test.clockshark.com`;

    // Step 1: Navigate to login page
    await page.goto('/Login');

    // Step 2: Click the "Sign up" link
    await page.getByRole('link', { name: 'Sign up' }).click();
    await expect(page).toHaveURL(/\/Signup/);

    // Steps 3 & 4: Fill email and password
    await page.getByRole('textbox', { name: 'Work Email' }).fill(email);
    await page.getByRole('textbox', { name: 'Password' }).fill('TestPass123!');

    // Step 5: Check terms and conditions
    await page.getByRole('checkbox', { name: /I agree to the ClockShark/ }).click();

    // Step 6: Submit signup — button label is "Try Free for 14 Days"
    await page.getByRole('button', { name: 'Try Free for 14 Days' }).click();

    // Step 7: Wait for redirect to onboarding welcome page
    await expect(page).toHaveURL(/\/App\/Welcome/, { timeout: 30000 });

    // Step 8: Onboarding Step 1 — personal info
    await page.getByLabel('First Name').fill('Test');
    await page.getByLabel('Last Name').fill('User');
    await page.getByLabel('Work Phone').fill('5551234567');

    // Step 9: Proceed to Step 2
    await page.locator('#step-1').getByText('Next').click();

    // Steps 10–14: Onboarding Step 2 — company info
    await page.getByLabel('Company Name').fill('E2E Test Company');
    await page.getByLabel('Industry Type').selectOption('Construction');
    await page.getByLabel('Number of Employees').selectOption('1-10');
    await page.getByLabel('Country', { exact: true }).selectOption('United States');
    // State/Province appears after selecting United States
    await page.getByLabel('State / Province').selectOption('California');

    // Step 15: Proceed to Step 3
    await page.locator('#step-2').getByText('Next').click();

    // Step 16: Skip the mobile app prompt
    await page.getByText("I'll do this later").click();

    // Verify onboarding complete — redirected into the app
    await expect(page).toHaveURL(/\/App\//, { timeout: 15000 });
  });
});
